name: ROS2 source build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        # https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html
        generator: ['Unix Makefiles', 'Ninja']

    # build ROS2 from source
    # https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html

    steps:
      - name: set locale
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y locales
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8

      - name: add the ROS 2 apt repository
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

      - name: install development tools and ROS tools
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            build-essential \
            cmake \
            git \
            python3-colcon-common-extensions \
            python3-flake8 \
            python3-flake8-blind-except \
            python3-flake8-builtins \
            python3-flake8-class-newline \
            python3-flake8-comprehensions \
            python3-flake8-deprecated \
            python3-flake8-docstrings \
            python3-flake8-import-order \
            python3-flake8-quotes \
            python3-pip \
            python3-pytest \
            python3-pytest-cov \
            python3-pytest-repeat \
            python3-pytest-rerunfailures \
            python3-rosdep \
            python3-setuptools \
            python3-vcstool \
            wget
          sudo apt upgrade
          sudo rosdep init
          rosdep update
          sudo apt install --no-install-recommends -y ninja-build

      - name: get ROS 2 code and install dependencies using rosdep
        run: |
          mkdir -p ~/ros2_humble/src
          cd ~/ros2_humble
          wget https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos
          vcs import src < ros2.repos
          rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"

      - name: build the code in the workspace
        run: |
          cd ~/ros2_humble/
          export CMAKE_GENERATOR="${{ matrix.generator }}"
          colcon build --symlink-install
